name: booknotes

services:
  postgres:
    image: postgres:17.0-bookworm
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data
    profiles:
      - postgres
    ports:
      - 5432:5432


volumes:
  postgres:
