name: booknotes

services:
  postgres:
    image: postgres:17.0-bookworm
    restart: no
    shm_size: 128mb
    env_file: ./backend/.env
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./.docker/postgres/seed-postgres.sql:/docker-entrypoint-initdb.d/seed-postgres.sql
      - postgres:/var/lib/postgresql/data
    profiles:
      - postgres
    ports:
      - 5432:5432


volumes:
  postgres:
